### ISSUE TITLE
Error al enviar orden de compra especie D

### ISSUE THREAD

**Issue by joaco-git** [nacho-herrera/pyCocos#15]
¡Hola! Puedo enviar correctamente órdenes de compra y venta de instrumentos en ARS.

Al intentar lo mismo en especie D obtengo un error, por ejemplo:

>>> long_ticker = app.long_ticker(ticker="AL30D", settlement=app.settlements.T2, currency=app.currencies.USD)
>>> long_ticker
'AL30D-0003-C-CT-USD'

>>> order = app.submit_buy_order(long_ticker=long_ticker,quantity="1", price="55")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 482, in submit_buy_order
    if not self._validate_buy_order(payload):
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1136, in _validate_buy_order
    price_factor = self._get_price_factor(instrument_code, long_ticker, segment)
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1223, in _get_price_factor
    return self._get_instrument_snapshot_value_by_key(instrument_code, long_ticker, segment, "price_factor")
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1200, in _get_instrument_snapshot_value_by_key
    instrument_snapshot: List[Dict[str, Any]] = self.get_instrument_snapshot(
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 683, in get_instrument_snapshot
    return self.client.get_tickers(ticker, segment.value)
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/components/client.py", line 407, in get_tickers
    return self.api_request(urls.endpoints["tickers"].format(ticker, segment))
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/components/client.py", line 468, in api_request
    raise ApiException("Bad HTTP API Response")
pycocos.components.exceptions.ApiException: Bad HTTP API Response

Aparece el mismo error si ingreso cualquier cosa como long_ticker, por ej: 'AL30DLDLDLD-0003-C-CT-USD'
¿Me podrían indicar dónde le estoy errando? 
Desde ya, muchas gracias.

**Comment by salen11934** [comment]
Hola Joaquín? Pudiste solucionarlo? Me pasa lo mismo con todas las especies D. Nacho, podrás darnos soporte al respecto? Gracias!

**Comment by joaco-git** [comment]
Hola Salen, no pude solucionarlo. Lo que noté es que las órdenes de venta en general funcionan ok incluso en especie D, aunque hoy tuve el mismo error con una orden de venta puntual. ¿Será que esto no es un problema de pycocos, sino de la app de cocos? En tal caso, ¿habrá una forma de bypassear este problema?

**Comment by nacho-herrera** [comment]
Buenas, no habia visto antes, no se por que pero no recibi el mail. Hoy intento modificar la biblioteca para que no enmascare el error en una respuesta generica y tratar de ver de que se trata.

**Comment by nacho-herrera** [comment]
Buenas, ahi estuve debuggeando y encontre el error, actualiza con `pip install --upgrade --force-reinstall pycocos` y despues contame si te anduvo ok. Ahora esta cerrado el mercado, pero parece enviar bien la solicitud.

**Comment by joaco-git** [comment]
Hola Nacho, ahora aparece otro error:
>>> order2 = app.submit_buy_order(long_ticker='AL30D-0001-C-CT-USD',quantity='1', price='14')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 482, in submit_buy_order
    if not self._validate_buy_order(payload):
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1136, in _validate_buy_order
    price_factor = self._get_price_factor(global_instrument_code, long_ticker, segment)
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1223, in _get_price_factor
    return self._get_instrument_snapshot_value_by_key(instrument_code, long_ticker, segment, "price_factor")
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 1200, in _get_instrument_snapshot_value_by_key
    instrument_snapshot: List[Dict[str, Any]] = self.get_instrument_snapshot(
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/main.py", line 683, in get_instrument_snapshot
    return self.client.get_tickers(ticker, segment.value)
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/components/client.py", line 407, in get_tickers
    return self.api_request(urls.endpoints["tickers"].format(ticker, segment))
  File "/home/joaquin/.local/lib/python3.9/site-packages/pycocos/components/client.py", line 468, in api_request
    raise ApiException(f"Bad HTTP API Response. Error code: {response.status_code}. Server response {response.text}")
pycocos.components.exceptions.ApiException: Bad HTTP API Response. Error code: 400. Server response {"success":false,"message":"Field 'instrument_type' is invalid"}

**Comment by nacho-herrera** [comment]
Oka ahora con la rueda abierta lo reviso

**Comment by nacho-herrera** [comment]
Por lo que veo el problema es con Contado Inmediato, con 'AL30D-0003-C-CT-USD' me anduvo. Ahi trato de debuggear que problema hay cuando usas plazo T0
![image](https://github.com/nacho-herrera/pyCocos/assets/65458529/1af449b2-6f96-49a5-a61b-0f37199f19c1)
